### ISSUE TITLE
readable_streambuffer breaks with 4000 MB download case

### ISSUE THREAD

**Issue by SameerTi** [samcday/node-stream-buffer#34]
RangeError: Invalid typed array length
at new Uint8Array (native)
at allocate (buffer.js:98:17)
at new Buffer (buffer.js:49:12)
at increaseBufferIfNecessary (/opt/npm511/rc2/npmtestserver/node-linux-x64-4-1-1/npm-test-server/node_modules/node-stream-buffer-master/lib/readable_streambuffer.js:73:23)
at put (/opt/npm511/rc2/npmtestserver/node-linux-x64-4-1-1/npm-test-server/node_modules/node-stream-buffer-master/lib/readable_streambuffer.js:85:7)

**Comment by samcday** [comment]
I'm not really surprised about this :) Buffering 4000mb in memory seems like A Bad Idea, at least to me. If your use case really demands it, and you can find a way to patch this library to support it cleanly, I'm happy to accept a PR for it :)
